// <auto-generated />
namespace BookingHotels.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class id_to_Guid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(id_to_Guid));
        
        string IMigrationMetadata.Id
        {
            get { return "201708091636420_id_to_Guid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
