// <auto-generated />
namespace BookingHotels.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class users_and_roles_altering_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(users_and_roles_altering_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201708091127511_users_and_roles_altering_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
