// <auto-generated />
namespace BookingHotels.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class book_config : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(book_config));
        
        string IMigrationMetadata.Id
        {
            get { return "201708140709012_book_config"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
